//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FestispecEntities : DbContext
    {
        public FestispecEntities()
            : base("name=FestispecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Contactperson> Contactpersons { get; set; }
        public virtual DbSet<Festival> Festivals { get; set; }
        public virtual DbSet<Inspection> Inspections { get; set; }
        public virtual DbSet<Inspector> Inspectors { get; set; }
        public virtual DbSet<Inspectors_at_inspection> Inspectors_at_inspection { get; set; }
        public virtual DbSet<Inspectors_availability> Inspectors_availability { get; set; }
        public virtual DbSet<Law> Laws { get; set; }
        public virtual DbSet<Municipality> Municipalities { get; set; }
        public virtual DbSet<Possible_answer> Possible_answer { get; set; }
        public virtual DbSet<Questionnaire> Questionnaires { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<Roll> Rolls { get; set; }
        public virtual DbSet<Type_contacts> Type_contacts { get; set; }
        public virtual DbSet<Type_questions> Type_questions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
