//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festipec.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspections()
        {
            this.Inspectors_at_inspection = new HashSet<Inspectors_at_inspection>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<System.DateTime> finished { get; set; }
        public int festival_id { get; set; }
    
        public virtual Festivals Festivals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspectors_at_inspection> Inspectors_at_inspection { get; set; }
    }
}
