//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festipec.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laws
    {
        public int id { get; set; }
        public int municipality_id { get; set; }
        public string name { get; set; }
        public string website { get; set; }
        public string description { get; set; }
    
        public virtual Municipalities Municipalities { get; set; }
    }
}
