//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestispecWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotations
    {
        public int id { get; set; }
        public Nullable<decimal> price { get; set; }
        public System.DateTime approved { get; set; }
        public int festival_id { get; set; }
    
        public virtual Festivals Festivals { get; set; }
    }
}
